Fix sub polygons
JuliaGeo/Shapefile.jl pull request #85
Opened 2023-01-28 18:29 UTC by rafaqz

This PR lets us use and plot the internal `SubPolygon` and `LinearRing` objects.

These are not part of any shapefile, but you can get these from `getgeom(multipolygon, 1)` or `getring(multipolygon, 1)` so we should be able to plot them, and all GeoInterface methods should be defined for them too.

2023-02-01 19:41 UTC, visr requested changes
Could use some tests.

2023-02-01 19:41 UTC, visr commented on src/polygons.jl
> +GI.ismeasured(::GI.LinearRingTrait, lr::LinearRing) = isnothing(lr.m)
```suggestion
GI.ismeasured(::GI.LinearRingTrait, lr::LinearRing) = !isnothing(lr.m)
```

2023-04-30 09:51 UTC, rafaqz commented
"some tests" turned into quite a mission.

We were returning coordinates without `M` values in them so there were some inconsistencies with GeoInterface `ncoord`/`ismeasured`/`is3d`/`coordnames`/`coordinates` not lining up.

Adding some tests for that and for plotting. But now that M coordinates have M in them, they don't plot :frowning_face:

2023-05-22 12:36 UTC, rafaqz commented
Also as noted in other threads, I cant reproduce these errors locally, so I cant finish this. If anyone can, please chime in with a fix.

2023-05-23 20:32 UTC, visr commented
Just rebased this, and saw the same error as in CI.

The plot failed because there was a MethodError on GeoInterfaceRecipes._coordvecs. That method was added in https://github.com/JuliaGeo/GeoInterface.jl/commit/5520d68e3216847e07ee4b207571af0f455f1e84, but this commit has not yet been released. And you probably are running it on master :)

```julia
using GeoInterfaceRecipes
s = LinearRing{Point}(view(points, 1:4))
GeoInterfaceRecipes._coordvecs(GI.trait(s), s)
plot(s)
```

2023-05-23 21:19 UTC, rafaqz commented
Aah ok. Guess we need to bump that then

2023-05-25 20:22 UTC, merged